# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.11:latest

tasks:
  - name: Setup kedro pipeline template, .venv and install dependencies
    before: 
      sudo apt-get update
    command: |
      sudo apt-get install tree
      virtualenv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install kedro
      kedro new --starter=spaceflights-pandas-viz --name=pipeline
      cd pipeline/
      pip install -r requirements.txt
      pip install pyarrow fastparquet openpyxl
      git clone https://github.com/AdamPrzychodniPrivate/notebook-templates.git notebooks/

ports:
 - port: 8888  # Default Jupyter Notebook port
