# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.10:latest

tasks:
  - name: Setup .venv, install dependencies and build docker image for kedro pipeline
    before: 
      sudo apt-get update
    command: |
      sudo apt-get install tree
      virtualenv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install kedro 
      cd pipeline/
      pip install -r requirements.txt
      pip install kedro-docker
      pip install kedro-kubeflow
      kedro docker init
      kedro docker build

# jetbrains:
#   pycharm:
#     plugins:
#       - com.markskelton.one-dark-theme  
#       - monokai-pro  
#     prebuilds:
#       version: stable  # Use the stable version for prebuilds

# virtualenv venv
# source venv/bin/activate
# pip install --upgrade pip
# pip install kedro 
# cd pipeline/
# pip install -r requirements.txt
# kedro docker init
# kedro docker build

# pip install 'kedro<0.19.0,>=0.18.1' kedro-kubeflow kedro-docker
# kedro new --starter=spaceflights
# cd pipeline
# echo kedro-kubeflow >> src/requirements*
# kedro docker init
# docker tag pipeline:latest remote.repo.url.com/pipeline:latest

# pip uninstall s3fs
# 