# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.11:latest

tasks:
  - name: Setup .venv, install dependencies and build docker image for kedro pipeline
    before: 
      sudo apt-get update
    command: |
      sudo apt-get install tree
      virtualenv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install kedro
      cd pipeline/
      pip install -r requirements.txt
      pip install pyarrow fastparquet openpyxl
      jupyter lab --ServerApp.allow_remote_access=True --ServerApp.allow_origin='*' --ServerApp.ip='0.0.0.0' --port=8888 --ServerApp.token='' --ServerApp.disable_check_xsrf=True

# pip uninstall s3fs

ports:
  - port: 8888  # Default Jupyter Notebook port
