# Using this image because kedro works currently with python 3.11
image: gitpod/workspace-python-3.11:latest

tasks:
  - name: Setup kedro pipeline template, .venv and install dependencies
    before: 
      sudo apt-get update
    command: |
      sudo apt-get install tree
      virtualenv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install kedro
      kedro new --starter=spaceflights-pandas-viz --name=pipeline
      cd pipeline/
      pip install -r requirements.txt
      pip install pyarrow fastparquet openpyxl

# jupyter lab --ServerApp.allow_remote_access=True --ServerApp.allow_origin='*' --ServerApp.ip='0.0.0.0' --port=8888 --ServerApp.token='' --ServerApp.disable_check_xsrf=True

ports:
 - port: 8888  # Default Jupyter Notebook port
